### ISSUE TITLE
Completar a classe Funcionários.

### ISSUE THREAD

**Issue by DAlSantana** [DAlSantana/ProjetoColaborado#10]
Requer os atributos dos funcionários, sendo eles os mesmos de clientes.

**Comment by lfchaves18** [comment]
Esse é meu

**Comment by Yanni-Nadur** [comment]
![image](https://user-images.githubusercontent.com/56276332/69371811-54b8d280-0c7f-11ea-88ab-03140f86168a.png)

Deixa comigo!
